pages:
  image: node
  before_script:
    - pwd
  script:
    - free -h
    - df -h
    - npm --version
    - date
    - yarn install
    - date
    - yarn run ng --version
    - yarn run ng build --aot=true --prod --build-optimizer --verbose --progress=true --delete-output-path --extract-licenses --subresource-integrity --stats-json --output-path=public
    - date
    - free -h
    - du -sh public/
    - ls -a
    - pwd
    - ls -a
    - pwd
  artifacts:
    paths:
      - public

test:mypages:
  image: trion/ng-cli-karma
  script:
    - pwd 
    - ls -a
    - yarn install
    - yarn run ng test --progress false --watch=false
    - yarn run ng e2e

test:mypagesnatively:
  image: fedora
  script:
    - pwd 
    - ls -a
    - dnf update -yqq
    - dnf install which chromium nodejs nodejs-yarn -yqq
    - which node
    - export CHROME_BIN=/usr/bin/chromium-browser
    - node --version
    - npm --version
    - yarn --version
    - yarn install
    - yarn run ng test --no-watch --no-progress --browsers=ChromeHeadlessCI --code-coverage
    - yarn run ng e2e --protractor-config=e2e/protractor-ci.conf.js
